spring.datasource.url=jdbc:postgresql://localhost:5432/calendar_db
spring.datasource.username=calendar_user
spring.datasource.password=calendar_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8081